### PR TITLE
Add mh-luebeck.de

### PR DESCRIPTION
**Pull request by maxvfischer**
Added Lübeck Academy of Music: https://en.wikipedia.org/wiki/L%C3%BCbeck_Academy_of_Music

### CODE REVIEW

**Comment by maxvfischer** [comment]
I also added a bunch more art and dance universities in Germany

**Comment by maxvfischer** [comment]
Found two more

**Comment by maxvfischer** [comment]
Added 3 more universities

**Comment by yigitguler** [comment]
Could you please fix the conflicts? Thank you.

**Comment by maxvfischer** [comment]
@yigitguler Sorry for the extreamly late response. I've rebased on your master and also added another domain.

**Comment by yigitguler** [comment]
Thank you!

**Pull request merged**
