### PR TITLE
Added State info for some Pakistani Universities and removed fake Universities

### PR DESCRIPTION
**Pull request by zakawat**
Added `"state-province"` data for a lot of Pakistani Universities and removed some of those Universities that were fake or had fake or illegal campuses in Pakistan.
For more info you can visit [this link](http://www.hec.gov.pk/english/universities/Pages/AJK/Illegal-DAIs.aspx)

### CODE REVIEW

**Comment by yigitguler** [comment]
Thank you!

**Comment by zakawat** [comment]
No problem brother !!
@yigitguler During today session, I saw so many colleges and Standalone Institutes _(that can't be classified as Universities)_ inside the list, so my question is, isn't this list for Universities only _(as name suggests "university-domains-list")_ ...?

**Comment by yigitguler** [comment]
I am not sure. There was an issue related to this, but there wasn't a consensus or a general request as far as I can remember.

**Comment by zakawat** [comment]
**Q1)** Wana know how often is the API “http://universities.hipolabs.com/search?name=barani” updated _(after the JSON file content is changed)_ ...?

**Q2)** Wouldn't it be nice to provide a sample Python App that servers API ..? and a little Help on "HOW TO SET IT UP IN YOUR SYSTEM" ....?

**Comment by yigitguler** [comment]
1) About every month.
2) It actually exists: https://github.com/Hipo/university-domains-list-api

**Pull request merged**
