### PR TITLE
updated IPLeiria

### PR DESCRIPTION
**Pull request by henshin**
IPLeiria's domain was outdated. Added email subdomain as well.

### CODE REVIEW

**Comment by enisbt** [comment]
@henshin Travis build will fail until #103 merges. Error might not be caused by your changes.

**Comment by yigitguler** [comment]
@henshin Thanks for the contribution!
@enisbt could you please check why tests are failed?

**Comment by enisbt** [comment]
@yigitguler I've enabled the Travis CI plugin for this repository but .travis.yml file is in #103. Since there is no .travis.yml, test is failed.

**Comment by yigitguler** [comment]
Thank you!

**Pull request merged**
