### PR TITLE
Added States info of TWO universities of Pakistan

### PR DESCRIPTION
**Pull request by zakawat**
to “BIIT” and “BIMS” Universities

### CODE REVIEW

**Comment by zakawat** [comment]
@yigitguler If you accept this one, then I will be making more changes to the list. I will be adding state info for more countries INSHALLAH !!

**Comment by yigitguler** [comment]
Thank you!

**Comment by zakawat** [comment]
@yigitguler what should I do in case where University named **“XYZ”** is located in both state **“A”** and **“B”**

**Comment by yigitguler** [comment]
Good question @zakawat. I am not sure. Maybe we can set the state where rectorate of the university is present as the default state.

**Pull request merged**
