### PR TITLE
Added Ontario Tech, Langara College, and Point Park University

### PR DESCRIPTION
**Pull request by sphhax**
Added Ontario Tech, Langara College, and Point Park University

### CODE REVIEW

**Comment by yigitguler** [comment]
Could you please fix the conflict?

**Comment by sphhax** [comment]
I don't know what the conflicts are? this is my third PR to add these schools as the others were ignored.

Github claims there are conflicts but I see none.

**Comment by sphhax** [comment]
Langara had duplicate entries, so I resolved that but GitHub still claims there are conflicts.

**Comment by sphhax** [comment]
@yigitguler Resolved all conflicts.

**Comment by yigitguler** [comment]
Thank you!

**Pull request merged**
