### PR TITLE
Added Lingdong University of Science and Technology

### LINKED ISSUE #350: Lingdong University of Science and Technology
{
"web_pages": [
"http://www.ltu.edu.tw"
],
"name": "Lingdong University of Science and Technology",
"alpha_two_code": "TW",
"state-province": null,
"domains": [
"ltu.edu.tw"
],
"country": "Taiwan"
},

### PR DESCRIPTION
**Pull request by vishal-sharma-369**
Resolves #350

### CODE REVIEW

**Comment by yigitguler** [comment]
Hi, another PR caused a conflict. Can you please fix it?

**Comment by vishal-sharma-369** [comment]
Conflict is due to addition of comma (",") at the end of the last curly brace '}'. 

There is no issue with the conflict.
Please merge this PR.

**Comment by vishal-sharma-369** [comment]
I have resolved the conflict occuring due to comma myself. 
Now you can merge the PR.

**Comment by yigitguler** [comment]
Still not resolved :/

**Comment by vishal-sharma-369** [comment]
Sorry but I am not able to see the conflicts on my side.
On my side it is showing : Only those with write access to this repository can merge pull requests.
Screenshot from 2023-05-23 19-32-12

The resolve conflicts button is disabled on my side. Is this the same on your side.

**Comment by yigitguler** [comment]
Seems resolved. Thank you!

**Pull request merged**
