### PR TITLE
Added uuid creator

### PR DESCRIPTION
**Pull request by 7tg**

### CODE REVIEW

**Comment by yigitguler** [comment]
What is the aim of this PR?

**Comment by tayyipgo** [comment]
It is a solution for issue mentioned here https://github.com/Hipo/university-domains-list/issues/200

**Comment by yigitguler** [comment]
We are still not very sure if this approach will actually solve all the problems. Thank you for putting effort. We will review after deciding on the final strategy.

**Comment by yigitguler** [comment]
We discussed this issue and we believe that having an id will make the addition of new universities more difficult. Closing for now.

**Pull request closed without merging**
